### ISSUE TITLE
Some bugs with Pyglet

### ISSUE THREAD

**Issue by Qiiiiiiiiii** [wadimkehl/ssd-6d#11]
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    from rendering.utils import precompute_projections, build_6D_poses, verify_6D_poses
  File "/home/shenqi/SSD-6D/ssd-6d/rendering/utils.py", line 10, in <module>
    from rendering.renderer import Renderer
  File "/home/shenqi/SSD-6D/ssd-6d/rendering/renderer.py", line 8, in <module>
    app.use_app('Pyglet')   # Set backend
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/usr/local/lib/python3.5/dist-packages/vispy/app/application.py", line 223, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
Cannot connect to "None"

I run the code ,but there is some bugs. So could you please tell me how to solve it?

**Comment by wadimkehl** [comment]
Have you installed pyglet? It should be in your environment

**Comment by Qiiiiiiiiii** [comment]
@wadimkehl yes, I have installed pyglet. And I try many times to reconfigure my environment. But there is still this error.
```
Requirement already satisfied: Pyglet in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: future in /usr/local/lib/python3.5/dist-packages (from Pyglet)
```

**Comment by Qiiiiiiiiii** [comment]
@wadimkehl 
I run the code and get the error and I can't solve it.Could you please give me a help and tell me the reason? Thanks.

```
`I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:01:00.0
Total memory: 10.91GiB
Free memory: 10.58GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)
Loading obj_01.ply with vertex colors
Models: ['obj_01']
Views: 337
Inplanes: 18
Priors: (21222, 8)
Precomputing projections for each used model...
  0%|                                                   | 0/337 [00:00<?, ?it/s][]

Traceback (most recent call last):
  File "run.py", line 76, in <module>
    m.projections = precompute_projections(views, inplanes, bench.cam, m)
  File "/home/shenqi/SSD-6D/ssd-6d/rendering/utils.py", line 118, in precompute_projections
    box = [box.min(0)[1], box.min(0)[0], box.max(0)[1] + 1, box.max(0)[0] + 1]
  File "/home/shenqi/.local/lib/python3.5/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity`
```

**Comment by Shahdoust** [comment]
@Qiiiiiiiiii I am getting the same error here, could you solve it?

**Comment by wadimkehl** [comment]
Probably something changed upstream. I’ll have a look as soon as I find the time

**Comment by Qiiiiiiiiii** [comment]
@Shahdoust Which error do you get? The first or the second?

**Comment by Shahdoust** [comment]
@Qiiiiiiiiii the second one.

(ValueError: zero-size array to reduction operation minimum which has no identity`)

**Comment by Qiiiiiiiiii** [comment]
@Shahdoust I'm sorry that I have not solved it. Maybe we can wait the author to check.

**Comment by fabi92** [comment]
It seems like this happens when the camera.yml file is not found within the dataset since then simply the identity matrix is employed, which eventually leads to empty renderings. Should be fixed soon.

**Comment by wadimkehl** [comment]
Fixed in master!

**Comment by LeeBY2016** [comment]
@Qiiiiiiiiii did you solve this problem?

```
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    from rendering.utils import precompute_projections, build_6D_poses, verify_6D_poses
  File "/home/lby/env_lby/ssd_6d/ssd-6d/rendering/utils.py", line 10, in <module>
    from rendering.renderer import Renderer
  File "/home/lby/env_lby/ssd_6d/ssd-6d/rendering/renderer.py", line 8, in <module>
    app.use_app('pyglet')   # Set backend
  File "/home/lby/anaconda3/envs/ssd_6d_py3/lib/python3.6/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/lby/anaconda3/envs/ssd_6d_py3/lib/python3.6/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/lby/anaconda3/envs/ssd_6d_py3/lib/python3.6/site-packages/vispy/app/application.py", line 223, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
Cannot connect to "None"
```

and pyglet have been installed.
```
Requirement already satisfied: pyglet in /home/lby/anaconda3/envs/ssd_6d_py3/lib/python3.6/site-packages (1.3.2)
Requirement already satisfied: future in /home/lby/anaconda3/envs/ssd_6d_py3/lib/python3.6/site-packages (from pyglet) (0.16.0)
```

seems like 
`app.use_app('pyglet')   # Set backend`
in the ''rendering/renderer.py'' has problem.

**Comment by wadimkehl** [comment]
Apparently... could you try out another backend? It seems that something is wrong with your setup since I cannot reproduce your issue on multiple machines and OSes

https://github.com/vispy/vispy/issues/582 
https://github.com/vispy/vispy/issues/1356

**Comment by hhaAndroid** [comment]
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    from rendering.utils import precompute_projections, build_6D_poses, verify_6D_poses
  File "/home/hha/TfProjects/poseEsmt/ssd-6d/rendering/utils.py", line 10, in <module>
    from rendering.renderer import Renderer
  File "/home/hha/TfProjects/poseEsmt/ssd-6d/rendering/renderer.py", line 8, in <module>
    app.use_app('pyglet')   # Set backend
  File "/home/hha/.conda/envs/tensorflow_140/lib/python3.6/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/hha/.conda/envs/tensorflow_140/lib/python3.6/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/hha/.conda/envs/tensorflow_140/lib/python3.6/site-packages/vispy/app/application.py", line 223, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
list index out of range

**Comment by wadimkehl** [comment]
Have you tried to use another backend? As outline in the two links I provided?

**Comment by Wegnery219** [comment]
So What's the problem with "RuntimeError: Could not import backend "Pyglet":Could not create GL context"?

**Comment by aniruddhavpatil** [comment]
@LeeBY2016  @Qiiiiiiiiii 
This worked for me
`pip3 install glfw`

However, now I run into
`  File "/home/venom/.local/lib/python3.5/site-packages/vispy/gloo/glir.py", line 651, in set_shaders (type_ + ' shader', errormsg))`
`RuntimeError: Shader compilation error in vertex shader:`
` `
There is actually a blank line after the colon. What might be the issue?

**Comment by iris0329** [comment]
it is a backend problem, pyglet doesn't work for me, but pyqt5 works.

but still new errors:
```
Models: ['obj_01']
Views: 337
Inplanes: 18
Priors: (21222, 8)

Precomputing projections for each used model...
WARNING: could not connect to display 
WARNING: Could not load the Qt platform plugin "xcb" in "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), linuxfb (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), minimal (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), minimalegl (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), offscreen (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), xcb (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

bash: line 1: 34538 Aborted                 (core dumped) env "PYTHONPATH"="/root/.pycharm_helpers/pycharm_matplotlib_backend:/data/lirong/ssd-6d" "PYCHARM_MATPLOTLIB_PORT"="34243" "JETBRAINS_REMOTE_RUN"="1" "PYTHONIOENCODING"="UTF-8" "PYCHARM_HOSTED"="1" "QT_QPA_PLATFORM_PLUGIN_PATH"="/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" "PYTHONUNBUFFERED"="1" /usr/bin/python3.6 -u /data/lirong/ssd-6d/run.py --network /data/lirong/ssd-6d/data/hinterstoisser/model/hinterstoisser_obj_01.pb --dataset /data/lirong/ssd-6d/data/

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

**Comment by iris0329** [comment]
OK, I solved this problem. 
as the author of `vispy` said in [https://github.com/vispy/vispy/issues/1580](url)
this error may be caused by running this code by a SSH connection. remote server cannot display, it's for computing, so there are 2 sulotions:
1. you must run the code on a local GPU computer, not on remote server.
2. compute resources on remote server, display on your local non-GPU computer. but this solution will need you to change the code.

I solved this problem as `solution 1`
